name: CI JOBS

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # - name: print Calendar
      #   run: cal
      - name: print date
        run: date 


  job3:
    runs-on: windows-latest 
    needs: [job1]
    steps:
      - name: printing Calendar on windows
        run: powershell -command "Get-Date UFormat '%B %Y' | Out-Host; cal.exe"
  

  
  # job2:
  #   runs-on: macos-latest
  #   needs: [job1]
  #   steps:
  #     - name: printing the calendar
  #       run: cal 
  #     - name: printing the date 
  #       run: date 