name: CI JOBS

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: printing the calendar
        run: cal
      - name: printing the date
        run: date 

  job2:
    runs-on: macos-latest
    steps:
      - name: printing the calendar
        run: cal 
      - name: printing the date 
        run: date 

  job3:
    runs-on: windows-latest 
    steps:
      - name: printing date 
        run: Get-date 
        